version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
  pre_build:
    commands:
      - echo "Pre_build"
      - echo "Logging in to Amazon ECR"
      - $(aws ecr get-login  --no-include-email --region us-east-1)
  build:
    commands:
      - echo "Build"
      - echo "Entered build phase"
      - echo "Building Java"
      - cd  audit-authorization
      - mvn clean package
      - docker build -t service/authapp .
      - docker tag service/authapp 840658508063.dkr.ecr.us-east-1.amazonaws.com/ij089-pod1-audit:authapp

  post_build:
    commands:
      - echo "Post_build"
      - docker push 840658508063.dkr.ecr.us-east-1.amazonaws.com/ij089-pod1-audit:authapp
      - printf '[{"name":"authapp-container","imageUri":"%s"}]' 840658508063.dkr.ecr.us-east-1.amazonaws.com/ij089-pod1-audit:authapp > taskdefinition.json
      - cat taskdefinition.json

artifacts:
  files:
    - audit-authorization/taskdefinition.json